### ISSUE TITLE
빌드타임 에러 & 런타임 에러 수정하기

### ISSUE THREAD

**Issue by simeddk** [simeddk/Tore04_BasicSyntaxCPP#1]
## 에디터와 블프를 일체 손대지 않고, 소스코드만 수정해서 완수하셔야 합니다.

- 개요 : 제공하는 소스코드의 잘못된 부분을 찾아서 바로 잡으십시오 💯 
- 내가 원하는 결과(영상) :  https://youtu.be/fDt85wTqlKM
- 소스코드 받는 곳 : https://github.com/simeddk/Tore04_BasicSyntaxCPP/tree/Assignment
  -> 우측 상단의 `<>Code` 버튼 눌러서 나오는 `Download Zip`으로 받아주세요.
  -> 주의! 압축 풀고 `-Assignment` 키워드는 삭제해주세요. (경로에 특수문자가 있으면 되는 빌드라 하더라도 실패합니다.)
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/d484f1ea-d6a8-490a-aeed-a7c43d4ba935)
  -> 이런 이유로 Users 사용자 폴더나 Download 폴더에도 프로젝트를 넣으면 안됩니다.

```c++
애초에 에러가 있는 상태로 제공되는 프로젝트입니다, 당연히 프로젝트는 안 열릴 것입니다.
솔루션 파일부터 생성 후 빌드타임 에러(비주얼 스튜디오 상의 컴파일 에러)부터 수정해주세요.
``` 

### 1. 빌드타임 에러 수정
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/b9413c5e-c48c-40b6-abe9-cdcb3dd57b11)

-> 소스코드의 잘못된 부분들을 수정하여 빌드를 성공시킬 것(2군데)
-> `Tip` Output 탭에서 [1/6].. [2/6].. 컴파일 중 어느 파일에서 error 구문이 뜨는지 잘 봐주세요.
### 2. 런타임 에러 수정
-> 빌드가 성공했다 하더라도 에디터가 터질 겁니다. 찾아서 고치시오.(빌드 단계에서 찾았다면 더 좋구요)
### 3. 스폰이 되도록 수정
-> 이 시점에서 에디터를 열 수 있을 겁니다.
-> Maps/Assignment1.umap 맵으로 이동
-> 이 맵에만 특별한 GameMode가 적용됨.(초록색 큐브에 대한 OnActorClicked를 활성화 함)
-> 초록색 큐브를 클릭하면 BP_Ball이 스폰되어야 하지만, 실제로 스폰되지 않습니다. 고치시오
### 4. 제출 방법
-> 아래 댓글란에 제출할 것(아래 예제 댓글 참고)
-> "에러의 원인이 무엇이었고, 어떻게 수정하였다" 라고 쓰세요.

**Comment by someddk2** [comment]
너무 한거 아닌가요?

**Comment by simeddk** [comment]
예)
### 1. 빌드타임 에러1
-> 에러 메세지 : redefinition of variable inside scope
-> 발생 지점 : ACBall::BeginPlay()
-> 원인 : 지역변수 NumA가 중복됨
-> 해결 방법 : NumA 중 하나를 삭제함

### 2. 빌드타임 에러2
-> 에러 메세지 : Unresolved external symbol
-> 발생 지점 : ACBall::Tick()
-> 원인 : 함수의 프로토타입만 있고 구현부가 없다.
-> 해결 방법 : 구현부를 추가함

### 3. 런타임 에러1
-> 에러 메세지 : exception_access_violation
-> 발생 지점 : ACBall::IsReallySpawned()
-> 원인 : GetPlayer() 함수가 nullptr을 리턴하고 있었다.
-> 해결 방법 : GetPlayer 함수가 실제 주소를 리턴하도록 수정함
......

**Comment by hyeseo-dev** [comment]
남궁혜서

1. 빌드타임 에러 수정
1) Error Message: 
C:/workspace/Tore04_BasicSyntaxCPP/Source/ThirdPersonCPP/Assignment/CBall.h(5)
error : #include found after .generated.h file - the .generated.h file should always be the last #include in a header

해결방법: CBall.h  #include "CBall.generated.h" 위치 수정

수정 전
#include "CoreMinimal.h"
#include "CBall.generated.h"
#include "GameFramework/Actor.h"


수정 후
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "CBall.generated.h"

2) Error Message: C:\UE4\UE_4.25\Engine\Source\Runtime\CoreUObject\Public\Templates/SubclassOf.h(64): error C2027: use of undefined type 'ACBall'

해결방법 : CBallSpawner.cpp/전방 선언 클래스 #include "CBall.h"

수정 전
#include "CBallSpawner.h"
#include "Kismet/KismetMathLibrary.h"

수정 후
#include "CBallSpawner.h"
#include "Kismet/KismetMathLibrary.h"
#include "CBall.h"


2. 런타임 에러 수정
Unreal Editor Error Message : UE4Editor_ThirdPersonCPP!ACBall::ACBall() [C:\workspace\Tore04_BasicSyntaxCPP\Source\ThirdPersonCPP\Assignment\CBall.cpp:6

해결방법: CBall.cpp UStaticMeshComponent 생성 및 초기화

수정 전
ACBall::ACBall()
{
	RootComponent = MeshComp;
	MeshComp->SetSimulatePhysics(true);
}

수정 후
ACBall::ACBall()
{
	MeshComp = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComp"));
	RootComponent = MeshComp;
	MeshComp->SetSimulatePhysics(true);
}


3. 스폰이 되도록 수정

해결방법
1) CBallSpawner.h/ UPROPERTY(EditDefaultsOnly, Category = "Spawn") 선언하여 에디터에서 수정할 수 있도록 변경

수정 전
private:
	TSubclassOf<ACBall> BallClass;
수정 후
private:
	UPROPERTY(EditDefaultsOnly, Category = "Spawn")
	TSubclassOf<ACBall> BallClass;

2) 빌드 후 BP_CBallSpawner의 Ball Class를 BP_CBall로 수정

**Comment by jslee629** [comment]
이진성

빌드타임에러1
에러메시지 -> error: #include found after .generated.h file - the .generated.h file should always be the last #include in a header
발생 지점: CBall.h
원인 -> CBall.generated.h가 가장 마지막에 임포트 되어야 함
수정 -> #include "CBall.generated.h" 가 마지막에 오도록 수정

빌드타임에러2
에러메시지 -> error C2027: use of undefined type 'ACBall', error C2672: 'StaticClass': no matching overloaded function found
발생 지점: CBallSpawner.cpp
원인 -> ACBallSpawner 클래스에서 ACBall을 찾을 수 없음  
수정 -> #include "CBall.h" 추가

런타임에러1
에러메시지 -> EXCEPTION_ACCESS_VIOLATION reading address 0x00000000
발생 지점: ACBall::ACBall()
원인 -> ACBall 클래스의 멤버변수 MeshComp의 dangling pointer
수정 -> MeshComp = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComp")); 추가

스폰이 되도록 수정

1. ACBallSpawner::BallClass가 에디터에서 보이도록 UPRPERTY 추가 (EditDefaultsOnly)
2. Category = "Spawn" : ACBall이 스폰이 될 수 있게 UPROPERTY에 추가
3. 빌드 후 에디터에 들어가 BP_CBallSpawner의 Ball Class를 BP_CBall로 수정

**Comment by ehddnjs1200** [comment]
정동원


1. 빌드타임 에러1
-> 에러 메세지 :  E:/D3D/Tore04_BasicSyntaxCPP/Source/ThirdPersonCPP/Assignment/CBall.h(5): error : #include found after .generated.h file - the .generated.h file should always be the last #include in a header

-> 발생 지점 : CBall.h의 5줄
-> 원인 : #include - .generated.h이 헤더의 마지막 #include 되지 않음
-> 해결 방법 :  #include - .generated.h를 마지막에 #include 되도록 수정
수정 전
#include "CBall.generated.h"
#include "GameFramework/Actor.h"

수정 후
#include "GameFramework/Actor.h"
#include "CBall.generated.h"


2. 빌드타임 에러2

-> 에러 메세지 : E:\UE4\UE_4.25\Engine\Source\Runtime\CoreUObject\Public\Templates/SubclassOf.h(64): 오류 C2027: 정의되지 않은 형식 'ACBall' 사용
-> 발생 지점 : CBallSpawner.h 파일
-> 원인 : CBallSpawner.h 에서 ACBall을 정상적으로 정의 되어 있지 않음
-> 해결 방법 : #include "CBall.h" 추가

3. 런타임 에러1

-> 에러 메세지 : Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000
-> 발생 지점 : ACBallSpawner()
-> 원인 : MeshComp가 정의가 되어있지 않아 RootComponent가 NULL 값을 참조
-> 해결 방법 : MeshComp를 정의 후 RootComponent를 설정

수정 전
ACBall::ACBall()
{
	RootComponent = MeshComp;
	MeshComp->SetSimulatePhysics(true);
}

수정 후

ACBall::ACBall()
{
	MeshComp = CreateDefaultSubobject<UStaticMeshComponent>("MeshComp");
	SetRootComponent(MeshComp);
	MeshComp->SetSimulatePhysics(true);
}



4. 스폰 수정

-> 에러 메세지 : LogSpawn: Warning: SpawnActor failed because no class was specified
-> 발생 지점 : SpawnBall()
-> 원인 : 스폰 할 액터의 정보가 NULL 로 확인
-> 해결 방법 : 에디터에서 스폰 할 액터의 정보를 확인 및 수정할 수 있는 코드 추가

수정 전

UPROPERTY(EditDefaultsOnly, Category = "Spawn")
FVector2D SpawnOffset;

private:
TSubclassOf<ACBall> BallClass;

수정 후

UPROPERTY(EditDefaultsOnly, Category = "SpawnLocation")
FVector2D SpawnOffset;

UPROPERTY(EditDefaultsOnly, Category = "SpawnActor")
TSubclassOf<ACBall> BallClass;


에디터에서 확인할 수 있는 코드 생성 이후 조금 더 명확히 알 수 있도록
각각 스폰 위치 설정은 SpawnLocation로 스폰 할 액터는 SpawnActor로 이름을 설정

**Comment by yongstar98** [comment]
김용호

1.  빌드타임 에러1

- >에러 메세지 : G:/Tore04_BasicSyntaxCPP/Source/ThirdPersonCPP/Assignment/CBall.h(5): error : #include found after .generated.h file - the .generated.h file should always be the last #include in a header
-> 발생 지점 : CBall.h의 #include문
->원인 : generated.h 파일을 포함하는 순서가 잘못됨
->해결 방법 : generated.h파일을 마지막에 포함하도록 위치 변경해야 함

2. 빌드타임 에러2

- >에러 메세지 : G:\UE4\UE_4.25\Engine\Source\Runtime\CoreUObject\Public\Templates/SubclassOf.h(64): error C2027: use of undefined type 'ACBall'
->발생 지점 : CBallSpawner.h의 #include문
->원인 : CBallSpawner.h의 코드에서 ACBall 타입을 사용하나 컴파일을 돌렸을때 해당 타입의 정의를 찾지 못함.
->해결 방법 : #include "CBall.h"를 추가

3. 런타임 에러1

- >에러 메세지 : 
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000

0x00007ffeec7244dc UE4Editor-ThirdPersonCPP.dll!ACBall::ACBall() [G:\Tore04_BasicSyntaxCPP\Source\ThirdPersonCPP\Assignment\CBall.cpp:6]
->발생 지점 : CBall.ccp파일의 ACBall::ACBall()
-> 원인 :  MeshComp를 올바르게 초기화 되지 않음
->해결 방법 :  ACBall::ACBall()문의 맨 위쪽에 
 MeshComp = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComp"));
 추가하면서 MeshComp를 CreateDefaultSubobject로 초기화시키기
 
 4. 스폰이 되도록 수정
 
   1)CBallSpawner.h 파일에서 BallClass를 보이게 하기 위해 (UPROPERTY(EditAnywhere, Category = "Spawn"))추가
   수정 전
   private:
	TSubclassOf<ACBall> BallClass;
   수정 후
   private:
	UPROPERTY(EditAnywhere, Category = "Spawn")
	TSubclassOf<ACBall> BallClass;
    2) 빌드 후 다시 에디터를 키고 BP_CBallSpawner의 디테일패널에서 Spawn::Ball Class를 none에서 BP_CBall로 교체하면 됩니다

**Comment by Ren-ame** [comment]
김기범

**1. 빌드타임 에러1**

-> 에러 메세지 : D:/Unreal Project/Tore04_BasicSyntaxCPP/Source/ThirdPersonCPP/Assignment/CBall.h(5): error : #include found after .generated.h file - the .generated.h file should always be the last #include in a header
-> 발생지점 : CBall.h 파일의 5번째 줄
-> 원인 : generated.h 뒤에 GameFramework/Actor.h 가 존재
-> 해결 방법 :  GameFramework/Actor.h 를 generated.h 앞쪽에 가도록 수정

**2. 빌드타임 에러2**

-> 에러 메세지 : C:\Program Files\Epic Games\UE_4.25\Engine\Source\Runtime\CoreUObject\Public\Templates/SubclassOf.h(64): error C2027: use of undefined type 'ACBall'
-> 발생지점 : CBallSpawner.h 파일의 7번째 줄
-> 원인 : CBallSpawner.h 에서 ACBall이 정의되어있지 않음
-> 해결 방법 : CBallSpawner.h 에 CBall.h 를 include 한다

**3. 런타임 에러**

-> 에러 메세지 : 
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000

UE4Editor_ThirdPersonCPP!ACBall::ACBall() [D:\Unreal Project\Tore04_BasicSyntaxCPP\Source\ThirdPersonCPP\Assignment\CBall.cpp:6]
-> 발생지점 : CBall.cpp 파일의 6번째 줄
-> 원인 : CBall.cpp의 MeshComp가 NULL을 참조
-> 해결 방법 : 
{
	MeshComp = CreateDefaultSubobject<UStaticMeshComponent>("MeshComp");
	RootComponent = MeshComp;
	MeshComp->SetSimulatePhysics(true);
}
로 수정

**4. 공이 스폰 되도록 수정**

-> 에러 메세지 : LogSpawn: Warning: SpawnActor failed because no class was specified
-> 발생지점 : BP_CBallSpawner
-> 원인 : BP_CBallSpawner의 Spawn 카테고리의 Ball Class 부분에 None이라 되어있음
-> 해결 방법: CBallSpawner.h 의 TSubclassOf<ACBall> BallClass; 위에 UPROPERTY(EditDefaultsOnly, Category = "Spawn") 추가 후 BP_CBallSpawner 에서 Spawn 카테고리의 Ball Class 안에 BP_CBall을 넣는다

**Comment by HyeonLang** [comment]
1. 빌드타임 에러1
-> 에러 메세지 : error : #include found after .generated.h file - the .generated.h file should always be the last #include in a header
-> 발생 지점 : CBallSpawner.h 
-> 원인 : #include "CBall.generated.h"가 맨 뒤에서 호출되지 않음
-> 해결 방법 :  #include "CBall.generated.h"를 헤더 맨 뒷줄로 진행

2. 빌드타임 에러2
-> 에러 메세지 : error C2027:    ǵ              'ACBall'  (  )     ߽  ϴ . (깨짐)
-> 발생 지점 : CBallSpawner.cpp
-> 원인 : #include "CBall.h"가 존재하지 않음
-> 해결 방법 : #include "CBall.h" 추가

3. 런타임 에러1
-> 에러 메세지 :
-> 발생 지점 : CBall.cpp
-> 원인 : MeshComp가 NULL
-> 해결 방법 : MeshComp = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComp"));로 할당

4. 공이 스폰되도록 수정
5. -> 에러 메세지 :
-> 발생 지점 : CBallSpawner.h
-> 원인 : BallClass 멤버 변수에 아무 클래스값도 들어가지 않음
-> 해결 방법 : UPROPERTY를 통해 에디터에 노출시켜서 값을 할당
